### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by cmungall** [dcppc/metadata-matrix#1]
sorry this sounds unbelievably pedantic...

it's a bit more github-esque to have a repo name like `metadata-matrix` (no leading uppercase, minus rather than underscore)

it's super-easy to rename a repo, it will auto-direct URLs and git clients will auto-reroute

Feel free to close with no action.

**Comment by victor73** [comment]
Done! Just needed some additional permissions, but @ACharbonneau took care of it...
